#ifndef __VERSION_H__
#define __VERSION_H__
#define VER_MAJOR 0
#define VER_MINOR 10
#define VER_RELEASE_BLOCK 0
#define VER_RELEASE_MAIN  0
#define VER_BUILD 0

#define VERSION_BLOCK VER_MAJOR.VER_MINOR.VER_RELEASE_BLOCK.VER_BUILD
#define VERSION_MAIN  VER_MAJOR.VER_MINOR.VER_RELEASE_MAIN.VER_BUILD

#endif
